### PR TITLE
adding a more complex sample

### PR DESCRIPTION
**Pull request by saboco**
I hope it is ok to submit a PR without opening first an issue an discuss, but when looking for examples of how to use Fable.Recharts, it feels like there were no that much.

So, I made a little sample a bit more complex.

The sample is a complete fable app (elmish) with the classic counter and a pie chart with custom active shape based on [this sample](http://recharts.org/en-US/examples/CustomActiveShapePieChart) from [recharts](http://recharts.org) with some variants.

----
NB: I used some `Emit attributes` so I can use PascalCase on types on fsharp and render camelCase on Js, there is some way to do the same thing without the attributes?

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks @saboco, this is great! Yes, it's definitely OK to send the PR and have the discussion here :)

You're right in that having a more complex sample is a great idea! I can merge the PR now, but regarding your question about changing the case of interface/record members: this has been discussed a few times (as [in here](https://github.com/fable-compiler/Fable/issues/1861)). I personally would prefer to avoid it, because Fable has already several hacks to change the runtime representation of types and these already add complexity and often cause issues in some edge cases.

We sometimes use the `CompiledName` attribute to change the name of union cases in runtime, though unfortunately F# doesn't accept it in interface members (and I just notice Fable doesn't honor it in record members either). Another option, though it's just a small cosmetic change, it's to use the new `EmitProperty("foo")` attribute which is just an alias of `Emit("$0.foo{{=$1}}")`.

Let me know if you want to make changes to the PR. If not, I will just merge it :) Thanks again!

**Comment by saboco** [comment]
I can definitely change them for `EmitProperty("foo")`, it will be more readable.
I'm also OK on having the abstract members on `camelCase` if you prefer, but the F# linter will complain.

Please, tell me what do you prefer?

**Comment by MangelMaxime** [comment]
IHMO I do think using `camelCase` is better because it shows "less" magic for newcomers.

If people, want to use `Emit` then they are probably advance enough in the Fable ecosystem to do it by themselves.

**Comment by alfonsogarciacaro** [comment]
I personally prefer the camelCase when interacting with JS, less magic :) In order to appease the linter you can put a file named `Settings.FSharpLint` (note there's no .xml extension) in the repo root with the following content:

```xml
<?xml version="1.0" encoding="utf-8"?>
<FSharpLintSettings>
  <Analysers>
    <NameConventions>
      <Enabled>False</Enabled>
    </NameConventions>
  </Analysers>
</FSharpLintSettings>
```

**EDIT:** Hmm, apparently they've changed the format to JSON so you may need to changed that. Check "Configuration Files" here: http://fsprojects.github.io/FSharpLint/

**Comment by saboco** [comment]
Ok, I'll make the changes

**Comment by saboco** [comment]
I have added the `fsharplint.json` file to use `camelCase` on `memberNames` and so modified the abstract members to be in `camelCase`.
I think we can merge if you don't see any other problem.

---
I have another question though: the ActiveShape function does not fire on the first load, as opposed to [the example in the recharts page](http://recharts.org/en-US/examples/CustomActiveShapePieChart), why could this be?

**Comment by alfonsogarciacaro** [comment]
Thanks again @saboco. Hmm, not sure about the ActiveShape callback, I'll have a look.

**Comment by alfonsogarciacaro** [comment]
Seems to be the `ActiveIndex` prop signature. [If I change it to `ActiveIndex of int`](https://github.com/fable-compiler/fable-recharts/commit/eee524c81049141f953051c8d56474e6fd881972#diff-b9dd8ec9ef238b9c0bf6861a193bcb52) it seems to work. Should I push a new release with that fix?

**Comment by saboco** [comment]
I don't think so @alfonsogarciacaro , the utility of the array is to have several sectors selected at the same time.
I tested an having more than one element in the array brakes the `ActiveShape` completly, still there is no errors on the console.

**Pull request merged**
